openapi: 3.0.0
info:
  title: Seduhin API
  description: API Backend untuk Sistem Kasir Kafe Seduhin
  version: 1.0.0
servers:
  - url: http://tubes_pbo_seduhin.test
paths:
  /public/menus:
    get:
      summary: Ambil semua menu
      responses:
        '200':
          description: Sukses
  /public/orders:
    post:
      summary: Buat pesanan baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nama_pelanggan:
                  type: string
                items:
                  type: array
      responses:
        '201':
          description: Created
    get:
      summary: Lihat semua pesanan
      responses:
        '200':
          description: Sukses